# Generated by Django 6.0.5 on 2026-05-25 12:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='products.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='stores.store')),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
                'db_table': 'inventory_inventory',
                'indexes': [models.Index(fields=['store'], name='inventory_i_store_i_44ca7e_idx'), models.Index(fields=['product'], name='inventory_i_product_f4f8f8_idx'), models.Index(fields=['available'], name='inventory_i_availab_fc9609_idx'), models.Index(fields=['price'], name='inventory_i_price_0c2fd1_idx'), models.Index(fields=['created_at'], name='inventory_i_created_4ce036_idx'), models.Index(fields=['deleted_at'], name='inventory_i_deleted_4a94e2_idx')],
                'constraints': [models.UniqueConstraint(fields=('store', 'product'), name='unique_store_product')],
            },
        ),
    ]
