# Generated by Django 6.0.5 on 2026-05-25 12:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('icon', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories_category',
                'indexes': [models.Index(fields=['name'], name='categories__name_e3ad98_idx'), models.Index(fields=['created_at'], name='categories__created_6b010e_idx'), models.Index(fields=['deleted_at'], name='categories__deleted_c31045_idx')],
            },
        ),
    ]
