# Generated by Django 6.0.5 on 2026-05-25 12:51

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Favorite',
                'verbose_name_plural': 'Favorites',
                'db_table': 'reviews_favorite',
                'indexes': [models.Index(fields=['user'], name='reviews_fav_user_id_825955_idx'), models.Index(fields=['product'], name='reviews_fav_product_c8cec4_idx'), models.Index(fields=['created_at'], name='reviews_fav_created_ff2f8a_idx'), models.Index(fields=['deleted_at'], name='reviews_fav_deleted_056599_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'product'), name='unique_user_product_favorite')],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='stores.store')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews_review',
                'indexes': [models.Index(fields=['user'], name='reviews_rev_user_id_a65d48_idx'), models.Index(fields=['store'], name='reviews_rev_store_i_e37743_idx'), models.Index(fields=['rating'], name='reviews_rev_rating_2db6dd_idx'), models.Index(fields=['created_at'], name='reviews_rev_created_bdcc91_idx'), models.Index(fields=['deleted_at'], name='reviews_rev_deleted_2e4e08_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'store'), name='unique_user_store_review')],
            },
        ),
    ]
